# Generated by Django 3.0.5 on 2021-05-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Make')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Model')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='newcars/')),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('mileage', models.CharField(max_length=20)),
                ('fuel', models.CharField(max_length=20)),
                ('engine_size', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=20)),
                ('gear_box', models.CharField(max_length=20)),
                ('seats', models.CharField(max_length=20)),
                ('doors', models.CharField(max_length=20)),
                ('colors', models.CharField(max_length=100)),
                ('make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Make')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Model')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Variant')),
            ],
        ),
    ]
