# Generated by Django 3.0.5 on 2021-05-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20210516_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
