# Generated by Django 3.0.5 on 2021-05-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_car_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='make',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ('name',)},
        ),
    ]
