# Generated by Django 3.0.5 on 2021-05-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_car_dealer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('id',)},
        ),
    ]
