# Generated by Django 3.0.5 on 2021-05-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20210517_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ('make', 'name')},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ('make', 'model', 'name')},
        ),
        migrations.RemoveField(
            model_name='car',
            name='dealer',
        ),
    ]
