# Generated by Django 3.0.5 on 2021-05-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20210517_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('id',)},
        ),
    ]
