# Generated by Django 3.0.5 on 2021-05-19 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_messages'),
        ('models', '0016_color_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Dealer'),
        ),
    ]
