# Generated by Django 3.0.5 on 2021-05-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210510_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.User')),
                ('state', models.CharField(choices=[('', 'SELECT STATE'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Orissa', 'Orissa'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttaranchal', 'Uttaranchal'), ('West Bengal', 'West Bengal')], default='', max_length=50)),
                ('city', models.CharField(choices=[('', 'SELECT CITY'), ('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Ahmedabad', 'Ahmedabad'), ('Bangalore', 'Bangalore'), ('Chennai', 'Chennai'), ('Chandigarh', 'Chandigarh'), ('Coimbatore', 'Coimbatore'), ('Gurgaon', 'Gurgaon'), ('Hyderabad', 'Hyderabad'), ('Jaipur', 'Jaipur'), ('Kolkata', 'Kolkata'), ('Lucknow', 'Lucknow'), ('Noida', 'Noida'), ('Thane', 'Thane'), ('Patna', 'Patna'), ('Pune', 'Pune')], default='', max_length=50)),
            ],
            bases=('home.user', models.Model),
        ),
    ]
