# Generated by Django 3.0.5 on 2021-05-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dealer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',)},
        ),
    ]
