# Generated by Django 3.0.5 on 2021-05-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210516_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
