# Generated by Django 3.0.5 on 2021-05-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210517_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellcar',
            options={'ordering': ('id',)},
        ),
    ]
