# Generated by Django 3.0.5 on 2021-05-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210517_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcar',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
