# Generated by Django 3.0.5 on 2021-05-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_sellcar_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcar',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
