# Generated by Django 3.0.5 on 2021-05-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_sellcar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcar',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
        migrations.AddField(
            model_name='sellcar',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
        migrations.AddField(
            model_name='sellcar',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
        migrations.AddField(
            model_name='sellcar',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
        migrations.AddField(
            model_name='sellcar',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
        migrations.AddField(
            model_name='sellcar',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
    ]
